spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/kramerius_plus_db
#    username: postgres
#    password: changeit
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/dbchangelog.xml
  data:
    mongodb:
      auto-index-creation: true
      database: KrameriusPlus
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  #    cz.inqool.dl4dh.krameriusplus.config.LoggingRequestInterceptor: DEBUG
  main:
    allow-bean-definition-overriding: true
  interceptor:
    body: SHORT

springdoc:
  swagger-ui.path: /swagger

system:
  environment: DEV
  kramerius:
    code: nkp
    default-url: https://www.ndk.cz
    register-url: https://api.registr.digitalniknihovna.cz/api/libraries
  enrichment:
  #  should use only ALTO for now, OCR comes without information about word concatenation at the end of lines
  #  and ALTO processing does not make manual corrections (while OCR processing does)tr
    source: ALTO
    udpipe:
      api: http://lindat.mff.cuni.cz/services/udpipe/api/process
    nametag:
      api: http://lindat.mff.cuni.cz/services/nametag/api/recognize
    tei:
      api: http://localhost:5000/tei
    ndk:
      path: .
  json:
    serializeEmptyArrays: true
  security:
    mock: false
    secret: kramerius-plus
  export:
    tmp-dir: data/tmp

keycloak:
  auth-server-url: https://keycloak.sekan.eu
  realm: DL4DHFeeder
  resource: feeder
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true

active-mq:
  messaging:
    auto-consume: true
    min-listeners: 2
    max-listeners: 5

server:
  tomcat:
    mbeanregistry:
      enabled: true
  forward-headers-strategy: framework

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health,info