spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kramerius_plus_db
    username: postgres
    password: uzidem9izo
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate