spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/kramerius_plus_db
#    username: postgres
#    password: uzidem9izo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    changeLog: classpath:/dbchangelog.xml
  data:
    mongodb:
      auto-index-creation: true
      database: KrameriusPlus
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  batch:
    initialize-schema: always
    job:
      enabled: false
#    cz.inqool.dl4dh.krameriusplus.config.LoggingRequestInterceptor: DEBUG
  interceptor:
    body: SHORT

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

springdoc:
  swagger-ui.path: /swagger

system:
  kramerius: MZK
  enrichment:
  #  should use only ALTO for now, OCR comes without information about word concatenation at the end of lines
  #  and ALTO processing does not make manual corrections (while OCR processing does)
    source: ALTO
    udpipe:
      api: http://lindat.mff.cuni.cz/services/udpipe/api/process
    nametag:
      api: http://lindat.mff.cuni.cz/services/nametag/api/recognize
    tei:
      api: http://localhost:5000/tei
    ndk:
      path: todo
  json:
    serializeEmptyArrays: true

active-mq:
  queues:
    exporting-queue: export
    enriching-queue: enriching
  messaging:
    auto-consume: true