spring:
  datasource:
    url: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
    username:
    password:
  data:
    mongodb:
      auto-index-creation: true
      database: KrameriusPlus
      drop-on-start: false

logging:
  level:
    cz.inqool.dl4dh.krameriusplus.service.enricher.UDPipeService: OFF
    cz.inqool.dl4dh.krameriusplus.service.enricher.NameTagService: OFF

springdoc:
  swagger-ui.path: /swagger

kramerius:
#  api: https://kramerius5.nkp.cz
  api: https://kramerius.mzk.cz

enrichment:
#  should use only ALTO for now, OCR comes without information about word concatenation at the end of lines
#  and ALTO processing does not make manual corrections (while OCR processing does)
  source: ALTO
  udpipe:
    api: http://lindat.mff.cuni.cz/services/udpipe/api/process
  nametag:
    api: http://lindat.mff.cuni.cz/services/nametag/api/recognize
  tei:
    api: http://localhost:5000