apiVersion: apps/v1
kind: Deployment
metadata:
  name: kramerius-api
  labels:
    name: kramerius-api
    app: kramerius-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kramerius-api
  template:
    metadata:
      labels:
        name: kramerius-api
        app: kramerius-api
    spec:
      containers:
        - name: kramerius-api
          image: eu.gcr.io/inqool-1301/cz.inqool.kramerius/api:latest
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://root:password@127.0.0.1:27017/?gssapiServiceName=mongodb&connectTimeoutMS=30000"
            - name: SYSTEM_ENRICHMENT_TEI_API
              value: "http://10.3.240.31:5000/tei"
            - name: SPRING_ACTIVEMQ_BROKER-URL
              value: "tcp://kramerius-activemq:61616"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://127.0.0.1:5432/kramerius_plus_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "kramerius"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "changeit"
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "1000m"
              memory: "1152Mi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/data
              subPath: kramerius-api/data
        - name: kramerius-db
          image: mongo:5.0.2
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: KrameriusPlus
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: shared-storage
              mountPath: /data/db
              subPath: kramerius-api/mongodb
        - name: kramerius-db-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: password
            - name: ME_CONFIG_MONGODB_SERVER
              value: 127.0.0.1
            - name: ME_CONFIG_SITE_BASEURL
              value: "/db/"
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
        - name: kramerius-activemq
          image: eu.gcr.io/inqool-1301/cz.inqool.kramerius/activemq:latest
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "288Mi"
          ports:
            - name: http
              containerPort: 61616
              protocol: TCP
        - name: kramerius-postgresql
          image: postgres:14.2-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: changeit
            - name: POSTGRES_USER
              value: kramerius
            - name: POSTGRES_DB
              value: kramerius_plus_db
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: shared-storage
              mountPath: /var/lib/postgresql/data/
              subPath: kramerius-api/postgresqldb
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-storage

---
apiVersion: v1
kind: Service
metadata:
  name: kramerius-api
  labels:
    name: kramerius-api
    app: kramerius-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: mongo
  selector:
    name: kramerius-api
  clusterIP: 10.3.240.30
