apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kramerius-http
  namespace: production
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dl4dh.inqool.cz`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: kramerius-web
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kramerius-https
  namespace: production
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dl4dh.inqool.cz`)
      kind: Rule
      services:
        - name: kramerius-web
          port: 80
  tls:
    certResolver: default
